name: ingre_note_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  ingre_note_design_system:
    path: ../../packages/ingre_note_design_system
  cupertino_icons: ^1.0.8

  # ----------------------
  # State Management
  # ----------------------
  flutter_riverpod: ^2.4.1

  # ----------------------
  # Dependency Injection
  # ----------------------
  get_it: ^8.2.0
  injectable: ^2.3.0

  # ----------------------
  # Data Models
  # ----------------------
  freezed_annotation: ^2.3.2
  json_annotation: ^4.9.0

  # ----------------------
  # Env / Config
  # ----------------------
  flutter_dotenv: ^5.0.3

  # ----------------------
  # UI / Design
  # ----------------------
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
