import 'package:flutter/material.dart';
import 'package:ingre_note_design_system/components/buttons/in_button.dart';
import 'package:ingre_note_design_system/tokens/colors.dart';
import 'package:ingre_note_design_system/tokens/radius.dart';
import 'package:ingre_note_design_system/tokens/spacing.dart';

class SummarizwCard extends StatelessWidget {
  const SummarizwCard({super.key});

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;

    return Container(
      width: size.width * 0.8,
      padding: const EdgeInsets.all(INSpace.md),
      decoration: BoxDecoration(
        color: INColors.white,
        borderRadius: BorderRadius.circular(INRadius.lg),
        boxShadow: [
          BoxShadow(
            color: INColors.grey.withOpacity(0.3),
            spreadRadius: 2,
            blurRadius: 15,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            "สรุปเมนูอาหาร",
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: INSpace.xs),
          Text(
            "จำนวนเมนู 5 รายการ",
            style: Theme.of(context).textTheme.bodyMedium,
          ),
          const SizedBox(height: INSpace.sm),
          ListView.builder(
            shrinkWrap: true,
            itemCount: 5,
            itemBuilder: (context, index) {
              return Padding(
                padding: const EdgeInsets.only(bottom: INSpace.sm),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      "เมนูที่ ${index + 1}",
                      style: Theme.of(context).textTheme.bodyMedium,
                    ),
                    Text(
                      "4 เสิร์ฟ",
                      style: Theme.of(context).textTheme.bodyMedium,
                    ),
                  ],
                ),
              );
            },
          ),

          Divider(color: INColors.grey),
          const SizedBox(height: INSpace.sm),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text("วัตถุดิบ", style: Theme.of(context).textTheme.bodyLarge),
              Text("จำนวน", style: Theme.of(context).textTheme.bodyLarge),
            ],
          ),
          const SizedBox(height: INSpace.md),
          ListView.builder(
            shrinkWrap: true,
            itemCount: 3,
            itemBuilder: (context, index) {
              return Padding(
                padding: const EdgeInsets.only(bottom: INSpace.sm),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      "วัตถุดิบ ${index + 1}",
                      style: Theme.of(context).textTheme.bodyMedium,
                    ),
                    Text(
                      "100 g",
                      style: Theme.of(context).textTheme.bodyMedium,
                    ),
                  ],
                ),
              );
            },
          ),

          SizedBox(height: INSpace.lg),

          Center(
            child: INButton(label: "Generated by IngreNote", onPressed: () {}),
          ),
        ],
      ),
    );
  }
}
